gradio web ui
isl-org/DPT pull request #1
Opened 2021-03-30 05:28 UTC by AK391

created a web ui on gradio

2021-04-03 10:13 UTC, ranftlr requested changes
Thank you for your contribution. Unfortunately, we can't accept PRs that include file manipulations and shell commands (especially if accessible via the web).

However, I think this could be entirely avoided by actually integrating the model into the script, instead of calling the original demo scripts.

2021-04-03 10:13 UTC, ranftlr commented on demo.py
> +    run_cmd("rm -rf " + INPUT_DIR)
Executing `rm -rf` with paths that are constructed by a wep-app is very dangerous. I can't merge this with shell commands that are excecuted.

2021-04-03 10:13 UTC, ranftlr commented on run_monodepth.py
> +            enable_attention_hooks=False, #args.vis,
Any reason why this is hardcode in this PR?

2021-04-03 14:17 UTC, AK391 commented
@ranftlr Hi, thanks for reviewing, the way the current code is setup would require to make more changes to pass in a pil image instead of a file path, is it possible to add an inference module to the readme without running the command line commands?

2021-04-05 09:32 UTC, ranftlr commented
I think the best way would be to restructure this PR. The basic flow would would be 

1) Load the models outside the process function so that they remain in memory. An example of this strategy is in the gradio guide: https://www.gradio.app/ml_examples. Our models are up to 1.2 GB, loading them with every request makes every inference request much slower than it needs to be. Currently loading the model takes more time than processing the image. If total memory is an issue you could add a startup flag to pre-select the models that are loaded. 
2) Wrap inference code to do the appropriate input transform, pass to the right model, and perform any post-processing (up-sampling and creating of label overlays for segmentation, up-sampling and normalization for monodepth) that is necessary based on the model and task (see corresponding `run` functions that are currently called).
3) Create a function `process` that receives the PIL image and passes the image to the appropriate wrapper function.

The upside of this would be that the code would be (potentially much) faster and wouldn't require any shell commands.

2021-09-24 19:16 UTC, closed without merging